name: Release App

on:
    push:
      tags:
        - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      # Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
     
      - name: Extract version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV
    
          # Convert 1.2.3 â†’ 10203
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          VERSION_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      # Java for Android / Gradle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Cache Gradle (optional but recommended)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('android/**/*.gradle*', 'android/**/gradle-wrapper.properties') }}

      - name: Install deps (Bun)
        run: bun install --frozen-lockfile

      - name: Build SvelteKit
        run: bun run build

      - name: Capacitor Sync
        run: bunx cap sync android

      - name: Decode keystore
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/release.keystore

      - name: Build Release APK
        working-directory: android
        run: |
          echo "VERSION_NAME=$VERSION_NAME"
          echo "VERSION_CODE=$VERSION_CODE"
          KEYSTORE_PATH="$(pwd)/app/release.keystore"
          ./gradlew assembleRelease \
            -PVERSION_NAME="$VERSION_NAME" \
            -PVERSION_CODE="$VERSION_CODE" \
            -Pandroid.injected.signing.store.file="$KEYSTORE_PATH" \
            -Pandroid.injected.signing.store.password="$ANDROID_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$ANDROID_KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$ANDROID_KEY_PASSWORD"

      - name: Prepare release asset
        run: |
          cp android/app/build/outputs/apk/release/app-release.apk "svara_darshini_${GITHUB_REF_NAME}.apk"

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            svara_darshini_${{ github.ref_name }}.apk
